const data ={
    produtos:[
        {
            _id:'1',
            nome:'Nike Slim Shirt',
            categoria:'Shirts',
            imagem:'/images/p1.jpg',
            preco:120,
            contaNoEstoque:10,
            marca: 'Nike',
            avaliacao:4.8,
            numbAvaliacoes:10,
            descricao:'Produto de alta qualidade',
        },
        {
            _id:'2',
            nome:'Adidas fit Shirt',
            categoria:'Shirts',
            imagem:'/images/p2.jpg',
            preco:100,
            contaNoEstoque:40,
            marca: 'Adidas',
            avaliacao:3.5,
            numbAvaliacoes:10,
            descricao:'Produto de alta qualidade',
        },
        {
            _id:'3',
            nome:'Lacoste Free Shirt',
            categoria:'Shirts',
            imagem:'/images/p3.jpg',
            preco:220,
            contaNoEstoque:15,
            marca: 'Nike',
            avaliacao:4.8,
            numbAvaliacoes:17,
            descricao:'Produto de alta qualidade',
        },
        {
            _id:'4',
            nome:'Nike Slim Camisa',
            categoria:'Camisas',
            imagem:'/images/p4.jpg',
            preco:78,
            contaNoEstoque:5,
            marca: 'Nike',
            avaliacao:4.5,
            numbAvaliacoes:14,
            descricao:'Produto de alta qualidade',
        },
        {
            _id:'5',
            nome:'Puma Slim camisa',
            categoria:'Camisas',
            imagem:'/images/p5.jpg',
            preco:65,
            contaNoEstoque:12,
            marca: 'Puma',
            avaliacao:4.5,
            numbAvaliacoes:10,
            descricao:'Produto de alta qualidade',
        },
        {
            _id:'6',
            nome:'Adidas Slim Camisas',
            categoria:'Camisas',
            imagem:'/images/p6.jpg',
            preco:139,
            contaNoEstoque:0,
            marca: 'Adidas',
            avaliacao:4.5,
            numbAvaliacoes:15,
            descricao:'Produto de alta qualidade',
        },
        {
            _id:'7',
            nome:'Adidas Slim Camisas',
            categoria:'Camisas',
            imagem:'/images/p7.jpg',
            preco:4000,
            contaNoEstoque:1,
            marca: 'Adidas',
            avaliacao:4.5,
            numbAvaliacoes:15,
            descricao:'Produto de alta qualidade',
        },

    ]
}

export default data;